Soln 3197 my sql connector
despegar/flowly4j pull request #2
Opened 2023-08-01 14:36 UTC by gianluca-capelo

2023-08-02 13:40 UTC, avchevalier requested changes

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-core/src/main/java/com/flowly4j/core/session/Execution.java
> +@AllArgsConstructor
Por qué tuviste que hacerlo público?

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-core/src/main/java/com/flowly4j/core/session/Session.java
> +@AllArgsConstructor
Por qué tuviste que hacerlo público? Hace bastante ruido.
Mirando el resto creo que lo haría protegido para paquete, metiendo tus clases en el mismo.
Igual me queda la duda si tus clases no podrían extender de estas. ¿Qué te parece? Se podría sobreescribir el Getter para poner los mappings.

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-examplejpa/pom.xml
> +        </dependency>
Por qué tiene la dependencia del conector de mongo?

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-mongodb/src/main/java/com/flowly4j/mongodb/MongoDBRepository.java
> +
Me parece que habría que revertir este cambio, no tiene sentido haber tocado el conector de mongo, no?

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-jpa/src/main/java/com/flowly4j/jpa/SessionWrapper.java
> +@Table(name = "sessions")
Podemos poner un prefijo? Tipo que todas las tablas arranquen con WF_.
Y podemos usar mayúscula imprenta? Tanto para el nombre de las tablas como para las columnas.
WF_SESSION

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-jpa/src/main/java/com/flowly4j/jpa/SessionWrapper.java
> +                throw new RuntimeException(e);
OMG

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-jpa/src/main/java/com/flowly4j/jpa/SessionWrapper.java
> +                        throw new RuntimeException(e);
Me ponen nerviosa estas excepciones, aunque sea logueemos algo y pensemos si agregarle un texto o solo la lanzamos así sin más?

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-jpa/src/main/java/com/flowly4j/jpa/Product.java
> +public class Product {
Qué onda este Product? Cualquiera, no?

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-jpa/src/main/java/com/flowly4j/jpa/JpaFlowlyRepository.java
> +        //TODO SOLN: esta bien crear uno por cada consulta y luego cerrarlo?
No, yo creo que se abre una sesión, no se crea cada vez.

2023-08-02 13:40 UTC, avchevalier commented on flowly4j-jpa/src/main/java/com/flowly4j/jpa/JpaFlowlyRepository.java
> +            return Option.of(session.toSession(objectMapper));
Acá si no la encontrás vas a tirar excepción. Habría que chequearlo primero y devolver empty para ese caso.

2023-08-02 13:44 UTC, avchevalier commented
> Me quedan dos dudas con respecto a la implementacion que por el momento quedaron con el prefijo TODO SOLN:
> 
> * Por que razón en el connector para Mongodb utilizan dos object mapper distintos (con distintas configuraciones) ?
>   
>   * Uno para el contexto que se utiliza para serializar y deserializar variables
>   * Otro para el MongoClient (deserializa y serializa los json de la colección de mongodb)
>   * En este connector precisamos que sea el mismo, porque si no la serializacion que realizamos al guardar las variables en la base de datos como string y la serializacion que luego hace el flujo cuando quiere castear los Object a la clase pertinente falla. Falla porque los dos distintos que se usaban en Mongo usando diferente modulos de deserializacion para fechas.

Acá no sabría decir por qué usa distintos, pero nosotros podemos pasar las 2 veces el mismo y no habría problema. Si te parece que amerita investigarlo avisame y lo miro, no es algo que tenga presente.


> * En mi implementacion al nuevo connector (JpaFlowlyRepository) le pasamos un EntityManagerFactory y luego este cuando necesita hacer una consulta crea un EntityManager
>   
>   * Mi duda es si esto es eficiente, estuve investigando y vi que varios lo utlizan de este modo: un solo EntityManagerFactory y este crea a demanda, de todas formas creo que esta duda la podemos ir resolviendo cuando este implementada la conexion a la base de rondamon (No es necesario usar jpa en rondamon, ya que hibernate implementa las clases de jpa, o sea podriamos pasarla un Factory de hibernate a nuestro connector).

A priori diría que es raro estar creando un entityManager cada vez, pero quizás representa una conexión, porque en definitiva es una forma de gestionar tus entidades. Habría que leer un poco para corroborar.

2023-08-02 14:01 UTC, gianluca-capelo commented on flowly4j-jpa/src/main/java/com/flowly4j/jpa/Product.java
> +public class Product {
Siii perdon, use ese Product para testear la serializacion

2023-08-02 14:31 UTC, gianluca-capelo commented on flowly4j-examplejpa/pom.xml
> +        </dependency>
Quedo por otras pruebas, ya la flete

2023-08-07 12:07 UTC, gianluca-capelo commented on flowly4j-core/src/main/java/com/flowly4j/core/session/Session.java
> +@AllArgsConstructor
Sobre Extender la clase:
El problema con el que me tope al intentar esto es que los tipos de la librería varv no se mapean automáticamente en la base (Map y Option). 
Por eso, intenté implementar un AtributeConverter el Map, pero no encontré una forma de replicar el mapeo que tengo en la solución actual de utilizar una tabla auxiliar para guardar las variables (@CollectionTable).
La única forma que encontré es que el converter guarde todo el mapa como un string en una columna de la tabla usando el objectMapper, funciona pero rompe el modelo relacional.
Aca hay un ejemplo de como seria https://github.com/despegar/flowly4j/commit/f1f6633ab61c714d99d44e12faf11d7be7d395d6

2023-11-21 15:48 UTC, closed without merging